swagger: "2.0"
info:
  title: Charge Watcher
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /devices/{deviceID}/charge:
    post:
      tags:
      - chargewatch
      summary: updateCharge chargewatch
      operationId: chargewatch#updateCharge
      parameters:
      - name: deviceID
        in: path
        description: deviceID
        required: true
        type: string
      - name: object
        in: body
        required: true
        schema:
          type: object
          properties:
            chargeValue:
              type: integer
              example: 2340694536803664586
              format: int64
            charging:
              type: boolean
              example: false
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChargewatchUpdateChargeResponseBody'
            required:
            - device
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ChargewatchUpdateChargeStatusBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ChargewatchUpdateChargeStatusInternalServerErrorResponseBody'
      schemes:
      - http
  /devices/{deviceID}/chargeHistory:
    get:
      tags:
      - chargewatch
      summary: getChargeHistory chargewatch
      operationId: chargewatch#getChargeHistory
      parameters:
      - name: deviceID
        in: path
        description: deviceID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChargewatchGetChargeHistoryResponseBody'
            required:
            - chargeHistory
      schemes:
      - http
  /user/{userID}/devices:
    get:
      tags:
      - chargewatch
      summary: listDevices chargewatch
      operationId: chargewatch#listDevices
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChargewatchListDevicesResponseBody'
            required:
            - devices
      schemes:
      - http
    post:
      tags:
      - chargewatch
      summary: createDevice chargewatch
      operationId: chargewatch#createDevice
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        type: string
      - name: object
        in: body
        required: true
        schema:
          type: object
          properties:
            description:
              type: string
              description: description
              default: ""
              example: Asperiores quia qui blanditiis veritatis.
            name:
              type: string
              description: device name
              example: Quas perspiciatis rerum.
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChargewatchCreateDeviceResponseBody'
            required:
            - device
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ChargewatchCreateDeviceStatusInternalServerErrorResponseBody'
      schemes:
      - http
  /user/{userID}/devices/{deviceID}:
    post:
      tags:
      - chargewatch
      summary: updateDevice chargewatch
      operationId: chargewatch#updateDevice
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        type: string
      - name: deviceID
        in: path
        description: deviceID
        required: true
        type: string
      - name: object
        in: body
        required: true
        schema:
          type: object
          properties:
            chargeValue:
              type: integer
              description: value [0,100]
              example: 25
              minimum: 0
              maximum: 100
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChargewatchUpdateDeviceResponseBody'
            required:
            - device
      schemes:
      - http
definitions:
  ChargeHistoryResponseBody:
    title: ChargeHistoryResponseBody
    type: object
    properties:
      deviceID:
        type: string
        example: Dolore commodi sint vel dolor.
      logs:
        type: array
        items:
          $ref: '#/definitions/ChargeLogResponseBody'
        example:
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
    example:
      deviceID: Odit perferendis est nesciunt impedit.
      logs:
      - charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        deviceID: Optio sit et ipsa a delectus.
      - charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        deviceID: Optio sit et ipsa a delectus.
      - charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        deviceID: Optio sit et ipsa a delectus.
      - charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        deviceID: Optio sit et ipsa a delectus.
    required:
    - deviceID
    - logs
  ChargeLogResponseBody:
    title: ChargeLogResponseBody
    type: object
    properties:
      charge:
        $ref: '#/definitions/ChargeResponseBody'
      deviceID:
        type: string
        example: Dignissimos excepturi minima.
    example:
      charge:
        charging: true
        timestamp: 7448338722332200067
        value: 3165210663228818035
      deviceID: Porro vero iste incidunt ut fugit facilis.
    required:
    - deviceID
    - charge
  ChargeResponseBody:
    title: ChargeResponseBody
    type: object
    properties:
      charging:
        type: boolean
        example: true
      timestamp:
        type: integer
        example: 219179355378239605
        format: int64
      value:
        type: integer
        example: 1880074187023316376
        format: int64
    example:
      charging: true
      timestamp: 116957627193468970
      value: 1669092679813684791
    required:
    - value
    - charging
    - timestamp
  ChargewatchCreateDeviceResponseBody:
    title: ChargewatchCreateDeviceResponseBody
    type: object
    properties:
      device:
        $ref: '#/definitions/DeviceResponseBody'
    example:
      device:
        charge:
          charging: true
          timestamp: 8070575591676915436
          value: 8344681023334431344
        description: Vel veritatis.
        id: Ut reprehenderit doloribus iusto optio ut corporis.
        name: Sunt quae vitae sint sit ea.
        state: Totam et suscipit.
        userID: Accusamus sit excepturi non consequatur quia quas.
    required:
    - device
  ChargewatchCreateDeviceStatusInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: createDevice_StatusInternalServerError_response_body result type
      (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ChargewatchGetChargeHistoryResponseBody:
    title: ChargewatchGetChargeHistoryResponseBody
    type: object
    properties:
      chargeHistory:
        $ref: '#/definitions/ChargeHistoryResponseBody'
    example:
      chargeHistory:
        deviceID: Dolor dignissimos.
        logs:
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
    required:
    - chargeHistory
  ChargewatchListDevicesResponseBody:
    title: ChargewatchListDevicesResponseBody
    type: object
    properties:
      devices:
        type: array
        items:
          $ref: '#/definitions/DeviceResponseBody'
        example:
        - charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
        - charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
        - charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
    example:
      devices:
      - charge:
          charging: true
          timestamp: 8070575591676915436
          value: 8344681023334431344
        description: Vel veritatis.
        id: Ut reprehenderit doloribus iusto optio ut corporis.
        name: Sunt quae vitae sint sit ea.
        state: Totam et suscipit.
        userID: Accusamus sit excepturi non consequatur quia quas.
      - charge:
          charging: true
          timestamp: 8070575591676915436
          value: 8344681023334431344
        description: Vel veritatis.
        id: Ut reprehenderit doloribus iusto optio ut corporis.
        name: Sunt quae vitae sint sit ea.
        state: Totam et suscipit.
        userID: Accusamus sit excepturi non consequatur quia quas.
    required:
    - devices
  ChargewatchUpdateChargeResponseBody:
    title: ChargewatchUpdateChargeResponseBody
    type: object
    properties:
      device:
        $ref: '#/definitions/DeviceResponseBody'
    example:
      device:
        charge:
          charging: true
          timestamp: 8070575591676915436
          value: 8344681023334431344
        description: Vel veritatis.
        id: Ut reprehenderit doloribus iusto optio ut corporis.
        name: Sunt quae vitae sint sit ea.
        state: Totam et suscipit.
        userID: Accusamus sit excepturi non consequatur quia quas.
    required:
    - device
  ChargewatchUpdateChargeStatusBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: updateCharge_StatusBadRequest_response_body result type (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ChargewatchUpdateChargeStatusInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: updateCharge_StatusInternalServerError_response_body result type
      (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ChargewatchUpdateDeviceResponseBody:
    title: ChargewatchUpdateDeviceResponseBody
    type: object
    properties:
      device:
        $ref: '#/definitions/DeviceResponseBody'
    example:
      device:
        charge:
          charging: true
          timestamp: 8070575591676915436
          value: 8344681023334431344
        description: Vel veritatis.
        id: Ut reprehenderit doloribus iusto optio ut corporis.
        name: Sunt quae vitae sint sit ea.
        state: Totam et suscipit.
        userID: Accusamus sit excepturi non consequatur quia quas.
    required:
    - device
  DeviceResponseBody:
    title: 'Mediatype identifier: device; view=default'
    type: object
    properties:
      charge:
        $ref: '#/definitions/ChargeResponseBody'
      description:
        type: string
        example: Placeat totam error repellendus vel aut.
      id:
        type: string
        example: Sed exercitationem.
      name:
        type: string
        example: Ut laudantium.
      state:
        type: string
        example: Consequuntur ipsa vero assumenda dicta.
      userID:
        type: string
        example: Molestiae ducimus itaque neque adipisci voluptatem.
    description: DeviceResponseBody result type (default view)
    example:
      charge:
        charging: true
        timestamp: 7448338722332200067
        value: 3165210663228818035
      description: Odit saepe.
      id: Provident qui.
      name: Odit sint aut quis porro mollitia iste.
      state: Doloribus consequatur.
      userID: Ut temporibus doloribus.
    required:
    - id
    - userID
    - name
    - description
    - state
    - charge
