openapi: 3.0.3
info:
  title: Charge Watcher
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /devices/{deviceID}/charge:
    post:
      tags:
      - chargewatch
      summary: updateCharge chargewatch
      operationId: chargewatch#updateCharge
      parameters:
      - name: deviceID
        in: path
        description: deviceID
        required: true
        schema:
          type: string
          description: deviceID
          example: Modi repellat eos.
        example: Et repudiandae animi animi.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chargeValue:
                  type: integer
                  example: 1266420597188454611
                  format: int64
                charging:
                  type: boolean
                  example: true
              example:
                chargeValue: 6893099211800512037
                charging: false
            example:
              chargeValue: 3290636200137892453
              charging: true
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceResponseBody'
              example:
                device:
                  charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /devices/{deviceID}/chargeHistory:
    get:
      tags:
      - chargewatch
      summary: getChargeHistory chargewatch
      operationId: chargewatch#getChargeHistory
      parameters:
      - name: deviceID
        in: path
        description: deviceID
        required: true
        schema:
          type: string
          description: deviceID
          example: Nostrum earum magnam dolores velit blanditiis nobis.
        example: Ut odit sit rerum.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetChargeHistoryResponseBody'
              example:
                chargeHistory:
                  deviceID: Dolor dignissimos.
                  logs:
                  - charge:
                      charging: true
                      timestamp: 7448338722332200067
                      value: 3165210663228818035
                    deviceID: Optio sit et ipsa a delectus.
                  - charge:
                      charging: true
                      timestamp: 7448338722332200067
                      value: 3165210663228818035
                    deviceID: Optio sit et ipsa a delectus.
                  - charge:
                      charging: true
                      timestamp: 7448338722332200067
                      value: 3165210663228818035
                    deviceID: Optio sit et ipsa a delectus.
  /user/{userID}/devices:
    get:
      tags:
      - chargewatch
      summary: listDevices chargewatch
      operationId: chargewatch#listDevices
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        schema:
          type: string
          description: userID
          example: Voluptate quia.
        example: Minima atque aut aut rerum autem cum.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDevicesResponseBody'
              example:
                devices:
                - charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
                - charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
                - charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
                - charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
    post:
      tags:
      - chargewatch
      summary: createDevice chargewatch
      operationId: chargewatch#createDevice
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        schema:
          type: string
          description: userID
          example: Molestiae iusto consequatur praesentium quia.
        example: Voluptatem facilis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: description
                  default: ""
                  example: Iusto nesciunt et nobis quasi tenetur.
                name:
                  type: string
                  description: device name
                  example: Eligendi ipsum veniam voluptas ullam voluptatem odit.
              example:
                description: Enim dignissimos harum sit est.
                name: Recusandae id reiciendis vitae.
            example:
              description: Et doloribus sed iusto.
              name: Odio eius tempore.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceResponseBody'
              example:
                device:
                  charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /user/{userID}/devices/{deviceID}:
    post:
      tags:
      - chargewatch
      summary: updateDevice chargewatch
      operationId: chargewatch#updateDevice
      parameters:
      - name: userID
        in: path
        description: userID
        required: true
        schema:
          type: string
          description: userID
          example: Dolores harum occaecati.
        example: Blanditiis recusandae quae sint.
      - name: deviceID
        in: path
        description: deviceID
        required: true
        schema:
          type: string
          description: deviceID
          example: Soluta corrupti eos omnis sint.
        example: Nam illo velit reiciendis aut qui quidem.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chargeValue:
                  type: integer
                  description: value [0,100]
                  example: 38
                  minimum: 0
                  maximum: 100
              example:
                chargeValue: 30
            example:
              chargeValue: 52
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeviceResponseBody'
              example:
                device:
                  charge:
                    charging: true
                    timestamp: 8070575591676915436
                    value: 8344681023334431344
                  description: Vel veritatis.
                  id: Ut reprehenderit doloribus iusto optio ut corporis.
                  name: Sunt quae vitae sint sit ea.
                  state: Totam et suscipit.
                  userID: Accusamus sit excepturi non consequatur quia quas.
components:
  schemas:
    Charge:
      type: object
      properties:
        charging:
          type: boolean
          example: true
        timestamp:
          type: integer
          example: 1938870607373076285
          format: int64
        value:
          type: integer
          example: 1733697141782441873
          format: int64
      example:
        charging: true
        timestamp: 6956020280378917234
        value: 1068213625239419291
      required:
      - value
      - charging
      - timestamp
    ChargeHistory:
      type: object
      properties:
        deviceID:
          type: string
          example: Expedita quia.
        logs:
          type: array
          items:
            $ref: '#/components/schemas/ChargeLog'
          example:
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
      example:
        deviceID: Delectus nam quia soluta ut.
        logs:
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
        - charge:
            charging: true
            timestamp: 7448338722332200067
            value: 3165210663228818035
          deviceID: Optio sit et ipsa a delectus.
      required:
      - deviceID
      - logs
    ChargeLog:
      type: object
      properties:
        charge:
          $ref: '#/components/schemas/Charge'
        deviceID:
          type: string
          example: Occaecati ratione.
      example:
        charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        deviceID: Deleniti corporis quia saepe alias sequi.
      required:
      - deviceID
      - charge
    CreateDeviceResponseBody:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
      example:
        device:
          charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
      required:
      - device
    Device:
      type: object
      properties:
        charge:
          $ref: '#/components/schemas/Charge'
        description:
          type: string
          example: Earum rerum quasi qui cum quo cumque.
        id:
          type: string
          example: Provident consequatur beatae in eveniet et dignissimos.
        name:
          type: string
          example: Laboriosam doloremque aliquam delectus iure blanditiis.
        state:
          type: string
          example: Adipisci quas cum qui.
        userID:
          type: string
          example: Qui est et alias assumenda et voluptatem.
      example:
        charge:
          charging: true
          timestamp: 7448338722332200067
          value: 3165210663228818035
        description: Iure voluptatum quia nesciunt.
        id: Asperiores sequi.
        name: Eveniet commodi dignissimos inventore est repudiandae.
        state: Ut consequatur rerum explicabo qui eaque.
        userID: Voluptates modi aut consequatur.
      required:
      - id
      - userID
      - name
      - description
      - state
      - charge
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetChargeHistoryResponseBody:
      type: object
      properties:
        chargeHistory:
          $ref: '#/components/schemas/ChargeHistory'
      example:
        chargeHistory:
          deviceID: Dolor dignissimos.
          logs:
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
          - charge:
              charging: true
              timestamp: 7448338722332200067
              value: 3165210663228818035
            deviceID: Optio sit et ipsa a delectus.
      required:
      - chargeHistory
    ListDevicesResponseBody:
      type: object
      properties:
        devices:
          type: array
          items:
            $ref: '#/components/schemas/Device'
          example:
          - charge:
              charging: true
              timestamp: 8070575591676915436
              value: 8344681023334431344
            description: Vel veritatis.
            id: Ut reprehenderit doloribus iusto optio ut corporis.
            name: Sunt quae vitae sint sit ea.
            state: Totam et suscipit.
            userID: Accusamus sit excepturi non consequatur quia quas.
          - charge:
              charging: true
              timestamp: 8070575591676915436
              value: 8344681023334431344
            description: Vel veritatis.
            id: Ut reprehenderit doloribus iusto optio ut corporis.
            name: Sunt quae vitae sint sit ea.
            state: Totam et suscipit.
            userID: Accusamus sit excepturi non consequatur quia quas.
          - charge:
              charging: true
              timestamp: 8070575591676915436
              value: 8344681023334431344
            description: Vel veritatis.
            id: Ut reprehenderit doloribus iusto optio ut corporis.
            name: Sunt quae vitae sint sit ea.
            state: Totam et suscipit.
            userID: Accusamus sit excepturi non consequatur quia quas.
      example:
        devices:
        - charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
        - charge:
            charging: true
            timestamp: 8070575591676915436
            value: 8344681023334431344
          description: Vel veritatis.
          id: Ut reprehenderit doloribus iusto optio ut corporis.
          name: Sunt quae vitae sint sit ea.
          state: Totam et suscipit.
          userID: Accusamus sit excepturi non consequatur quia quas.
      required:
      - devices
